version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/spree_wishlist # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/ruby:2.5-node-browsers # ...with this image as the primary container; this is where all `steps` will run
        environment: # environment variables for primary container
          CIRCLE_TEST_REPORTS: /tmp/test-results
          CIRCLE_ARTIFACTS: /tmp/test-artifacts
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: ~/spree_wishlist/vendor/bundle
          SPREE_USE_PAPERCLIP: true
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      - restore_cache:
          key: v1-phantomjs-2.1.1

      - run:
          name: Install phantomjs
          command: |
            if ! [ $(which phantomjs) ]; then
              sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
            fi

            sudo chmod ugo+x /usr/local/bin/phantomjs

      - save_cache:
          key: v1-phantomjs-2.1.1
          paths:
            - /usr/local/bin/phantomjs

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - spree_wishlist-bundle-v2-{{ .Branch }}
            - spree_wishlist-bundle-v2

      # Install gem dependencies
      - run:
          name: Bundle Install
          command: |
            bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: spree_wishlist-bundle-v2-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/spree_wishlist/vendor/bundle

      - run:
          name: Run rspec
          command: |
            RAILS_ENV=test bundle exec rake test_app
            RAILS_ENV=test bundle exec rake spec

      - store_artifacts:
          path: /tmp/test-artifacts
          destination: test-artifacts

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
